name: Prank
main: com.spikemeister.prank.PrankPlugin
version: 2.0
author: SpikeMeister
description: >
             Prank is a plugin which consists of a number of pranks which can be played on unsuspecting players.
commands:
  prank:
    description: Adds a player to the list of players to be pranked.
    usage: |
           /<command> [prank] [player]
           Example: /<command> creeper [player] - Starts creeper pranking "player".
           Example: /<command> toolswitch [player] - Starts tool switch pranking "player".
           Example: /<command> shockingfall [player] - Starts shocking fall pranking "player".
  unprank:
    description: Removes a player from the list of players to be pranked.
    usage: |
           /<command> [prank] [player]
           Example: /<command> creeper [player] - Stops creeper pranking "player".
           Example: /<command> toolswitch [player] - Stops tool switch pranking "player".
           Example: /<command> shockingfall [player] - Stops shocking fall pranking "player".

permissions:
    prank.*:
        description: Gives access to all prank commands
        children:
            prank.creeper: true
            prank.toolswitch: true
            prank.shockingfall: true
    prank.creeper:
        description: Allows you to creeper prank a user
        default: op
    prank.toolswitch:
        description: Allows you to tool switch prank a user
        default: op
    prank.shockingfall:
        description: Allows you to shocking fall prank a user
        default: op